### ISSUE TITLE
CLI: Admin user should not be listed before being actually created

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#1448]
When installing FreshRSS via cli, the install process creates a user whereas it should not create a user.

```bash
>sudo -u www-data ./cli/do-install.php --default_user myuser --api_enabled --db-type sqlite
FreshRSS install…
• Remember to create the default user: myuser
	./cli/create-user.php --user myuser --password 'password' --more-options
• Remember to re-apply the appropriate access rights, such as:
	sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
Result: success
>sudo -u www-data ./cli/list-users.php 
myuser
>sudo -u www-data ./cli/user-info.php -h --user myuser
FreshRSS error: user not found: myuser
```

The user is listed but does not exist. This is a bit inconsistent.

Why not set the default user not at *install* time, but at *user creation* time ?

This make it difficult to know whether I have to really create the user or not...

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/issues/1445 https://github.com/FreshRSS/FreshRSS/pull/1447

**Comment by Alkarex** [comment]
Should be fixed in https://github.com/Alkarex/FreshRSS/commit/ae1bf1f56fcfa920db3d5092cb18dced4cbcb434 / https://github.com/FreshRSS/FreshRSS/pull/1447

**Comment by oupala** [comment]
This bug is fixed.

But is it necessary to set the default user at install time?

Could it be possible that the default user is set at user creation time? The first created user would simply be the default one. In my opinion, this appears to be simpler. Don't you think?

**Comment by Alkarex** [comment]
This could be an option indeed. The historical reason is that there is a global configuration (including the name of the default user) and then user-specific configurations. Furthermore, it is more consistent with the possibility to reconfigure the default user to another user.

**Comment by oupala** [comment]
Historical reasons are usually bad reasons... ;-)

From a user point of view, what does it change for a user to be default one or not? Is he sort of an admin?

**Comment by Alkarex** [comment]
Historical was maybe a bad word: the situation is still the same. Yes, the default / admin user has additional rights (such as to create other users, change login type, etc.) and is also used for the content of the anonymous view.

**Comment by oupala** [comment]
I still think that admin user should be the first created user and hence should not be specified at install time. It would be more consistent.

An instance of FreshRSS without user cannot have a default admin user...
