### ISSUE TITLE
Cannot force feed addition

### ISSUE THREAD

**Issue by nicofrand** [FreshRSS/FreshRSS#2524]
Hi,

I cannot add the feed `https://mnapoli.fr/atom.xml#force_feed` even with `#force_feed` on.

Logs: `Unknown error for feed [https://mnapoli.fr/atom.xml]`

SimplePie does not work on it: https://simplepie.org/demo/?feed=https%3A%2F%2Fmnapoli.fr%2Fatom.xml but the atom feed seems OK: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fmnapoli.fr%2Fatom.xml

What did I miss?

Thanks in advance

**Comment by Frenzie** [comment]
I'm not sure what the issue could be. It works for me with `https://mnapoli.fr/atom.xml#force_feed`.

**Comment by Alkarex** [comment]
It also works for me with `https://mnapoli.fr/atom.xml#force_feed`
Please try again :-)
If it still does not work, we can test a bit more

**Comment by nicofrand** [comment]
I swear I tried a few times this morning and it failed.
I just tried again and it worked, even without `#force_feed`.

Could that be a network issue on my server? Would the log be the same in that case?

**Comment by nicofrand** [comment]
Same right now with `https://hugo-soltys.com/rss/articles.xml#force_feed`

![Screenshot_2019-09-16 Gestion des abonnements · FreshRSS](https://user-images.githubusercontent.com/3419050/64954355-a27f1c00-d885-11e9-822a-44fac15fbe0e.png)

![Screenshot_2019-09-16 Gestion des abonnements · FreshRSS(1)](https://user-images.githubusercontent.com/3419050/64954365-ab6fed80-d885-11e9-91f1-95654a517687.png)


> Unknown error for feed [https://hugo-soltys.com/rss/articles.xml]

**Comment by nicofrand** [comment]
I can't find anything useful in php-fpm logs, nor syslog.

**Comment by nicofrand** [comment]
BTW there is a french comment here: https://github.com/FreshRSS/FreshRSS/blob/master/app/Models/Feed.php#L310

**Comment by nicofrand** [comment]
I modified https://github.com/FreshRSS/FreshRSS/blob/master/app/Models/Feed.php#L299 a bit and now it logs  `[Mon, 16 Sep 2019 14:20:23 +0200] [warning] --- Unknown error for feed [https://hugo-soltys.com/rss/articles.xml]mtime=NULL.` with this code:

```php
throw new FreshRSS_Feed_Exception(
    ($errorMessage == '' ? 'Unknown error for feed' : $errorMessage) . ' [' . $url . ']' . 'mtime=' . var_export($mtime, true) . '.'
);
```

**Comment by nicofrand** [comment]
OK I think I got something: when adding it with `#force_feed`, then removing it then re-adding **without** `force_feed`, it works whereas it should not.

I think there is something wrong with the cache: if I clear it (`rm -rf data/cache/*`), and then re-add without `#force_feed` it fails as expected.

So, new STR:

1. Add `https://hugo-soltys.com/rss/articles.xml` (expect an error)
1. Add `https://hugo-soltys.com/rss/articles.xml#force_feed`: same error as before whereas I added the `force_feed` param.

If you directly try `https://hugo-soltys.com/rss/articles.xml#force_feed`, it will work. It needs to fail once to fail again.

**Comment by nicofrand** [comment]
BTW same as #2484.

**Comment by Alkarex** [comment]
Yes, we need to clear the local cache when the user changes the URL, otherwise one has to wait ~15+ minutes

**Comment by Alkarex** [comment]
Should be fixed with https://github.com/FreshRSS/FreshRSS/pull/2852
Tests welcome

**Comment by nicofrand** [comment]
Yup, works fine, thanks!

**Comment by Alkarex** [comment]
Great, thanks for the quick feedback :-)
Et bon confinement ! @nicofrand

**Comment by nicofrand** [comment]
Merci, de même !

**Comment by ghost** [comment]
bug still continues. i tried the above solution but it didn't work
not just one feed link either. It gives this error on all links.

![opera_TXOikkKkcQ](https://user-images.githubusercontent.com/61169988/137120679-2f88bdeb-a858-4209-855c-83f2694a5cd9.png)

**Comment by TheMystery28** [comment]
> bug still continues. i tried the above solution but it didn't work not just one feed link either. It gives this error on all links.
> 
> ![opera_TXOikkKkcQ](https://user-images.githubusercontent.com/61169988/137120679-2f88bdeb-a858-4209-855c-83f2694a5cd9.png)

The same for me with the latest version 
Help us please

**Comment by Frenzie** [comment]
Are you talking about the same feed or a different one?

**Comment by TheMystery28** [comment]
All feeds
https://www.royalroad.com/syndication/49879
I can't add anything

**Comment by Frenzie** [comment]
It works for me, no `#force_feed` necessary. What do the logs say?

**Comment by TheMystery28** [comment]
Thanks, I found the error.
I don't know why, but the Whitelist extension also affects the feed add... that's strange.

**Comment by Frenzie** [comment]
Also? That seems to be what it's for @aledeg? :-)

https://github.com/aledeg/xExtension-WhiteList
> A FreshRSS extension to validate that new feeds are allowed according to a white-list.
