### ISSUE TITLE
Unable to Configure FreshRSS

### ISSUE THREAD

**Issue by ProbablyBread** [FreshRSS/FreshRSS#2748]
Weird issue, can't find anyone who has encountered this issue (or maybe my GoogleFu is just weak). 

So I've successfully gotten here:
![image](https://user-images.githubusercontent.com/50959479/71614176-2ebf1000-2be5-11ea-8617-91334d49cae1.png)

After filling in the options and clicking Submit, the fields just get reset and it doesn't move on to the next page. There's no error message in both the Web UI and inside /var/log/nginx/error.log either.

But checking .../data/config.php, the fields for the database does get populated: 
![Untitled](https://user-images.githubusercontent.com/50959479/71614271-a42ae080-2be5-11ea-884c-3b866532e6ae.png)

Any help would be appreciated!

**Comment by Frenzie** [comment]
Duplicate of #2732?

**Comment by ProbablyBread** [comment]
Dropped the freshrss DB, created a new freshrss DB along with a new user of the same name. No luck. 

![Untitled](https://user-images.githubusercontent.com/50959479/71614959-9c6d3b00-2be9-11ea-8ab7-7cb642f8e840.png)

**Comment by Alkarex** [comment]
PostgreSQL is picky about localhost. Try 127.0.0.1 and make sure you have the latest FreshRSS version from our Master branch in which a PostgreSQL bug has just been fixed

**Comment by Alkarex** [comment]
Ups, and I can see an unrelated bug in base_url

**Comment by ProbablyBread** [comment]
I already have the latest version. 

Same issue after changing to 127.0.0.1 as well. Also tried to use 127.0.0.1:5432, but no luck with that either. 

For the record, I'm using Nginx and PHP 7.3 for this.

**Comment by Alkarex** [comment]
And if you drop the DB without manually creating it? (while giving the freshrss user rights to create a database)

**Comment by ProbablyBread** [comment]
Fixed it. I was trying to use nginx reverse proxy to get into freshrss.

Saw this issue (#1958  ) regarding nginx reverse proxy and tried accessing directly into http://URL/freshrss instead of http://URL/proxy-rss and it worked immediately.

Got the reverse proxy working with this as well, not sure if this is good practice: 
https://www.reddit.com/r/selfhosted/comments/dw83ew/freshrss_apache_reverse_proxy/

Thanks for your assistance!

**Comment by Alkarex** [comment]
@parkel42 If you find time, could you please try to make a few stress tests of installation with PostgreSQL? Like when the database already exists or not (FreshRSS is supposed to try to auto-create it), and with different user permissions (like when the database exists but the freshrss user does not have rights to create a database). 
I believe we might still have some cases we might not be handling properly https://github.com/FreshRSS/FreshRSS/pull/2735#discussion_r361846714

**Comment by ProbablyBread** [comment]
@Alkarex I have tested with the following: 

1. Database does not exist, user has rights to create DB - successful, database was automatically created. 

2. Database does not exist, user has rights to create DB but doesn't have a password - got this error message (expected):
`Verify your database information. : Access to database is denied for test-freshrss: SQLSTATE[08006] [7] fe_sendauth: no password supplied`

3. Database does not exist, user does not have rights to create DB - got this error message (expected): 
`Verify your database information. : Access to database is denied for test-freshrss: SQLSTATE[08006] [7] FATAL: database "test-freshrss" does not exist`

4. Database exists, user does not have rights to create DB - successful. 

Note that for all the above cases, the test-freshrss user was not assigned owner rights to any of the DBs that were either manually/automatically created. FreshRSS was still able to write to the DB without issues.

**Comment by Alkarex** [comment]
Thanks @parkel42, great feedback 👍 
So to summarize, there was no situation with a wrong FreshRSS behaviour, right?

**Comment by ProbablyBread** [comment]
@Alkarex Yep! No issues with the behaviour.
