### ISSUE TITLE
[Feature] adjust loglevel

### ISSUE THREAD

**Issue by Tone866** [FreshRSS/FreshRSS#7594]
### Is your feature request related to a problem? Please describe.

Are there more options to adjust the loglevel than production and debugging?
I don't need
```
2025-05-15T16:20:01.904303+02:00 PC FreshRSS[2045439]: FreshRSS SimplePie GET 200 https://explosm-1311.appspot.com/                                     │
│2025-05-15T16:20:01.921292+02:00 PC FreshRSS[2045439]: FreshRSS SimplePie uses cache for https://explosm-1311.appspot.com/
```
all the time.

### Describe the solution you’d like

at least one more option for "only warnings and above"

**Comment by sokai** [comment]
FYI: today I _fiddled_ a bit in my setup (because this behaviour _annoys_ me a bit, too) and could find one/a/the cause

See https://github.com/FreshRSS/FreshRSS/blob/3776e1e48f33e80eb4b674bb64b419caf3b5a4e2/app/Models/Feed.php#L464

There seems no check (or similar), like for example at https://github.com/FreshRSS/FreshRSS/blob/3776e1e48f33e80eb4b674bb64b419caf3b5a4e2/app/actualize_script.php#L31-L33

Maybe we can/should implement this in `app/Models/Feed.php`?
```php
if (!COPY_LOG_TO_SYSLOG && SIMPLEPIE_SYSLOG_ENABLED) {
    syslog(LOG_DEBUG, 'FreshRSS SimplePie uses cache for ' . $clean_url);
}
```

BR

---

BTW, I use the following cron-job (`crontab -e`) to only log errors from the feed updates to a log file:
```crontab
PHP="/usr/bin/php --define opcache.enable_cli=0 --define apc.enable_cli=1"
*/30 * * * * /usr/bin/ionice -c 3 /usr/bin/nice -n 5 $PHP -qf $PATH_FRESHRSS/app/actualize_script.php >>$PATH_ERRORS/FreshRSS.log 2>&1
```

**Comment by JamBalaya56562** [comment]
@sokai nailed it — that unguarded `syslog(LOG_DEBUG, 'FreshRSS SimplePie uses cache for …')` in `app/Models/Feed.php` was exactly the leak. It is now fixed in #8986 (merged): both that line and the `FreshRSS SimplePie GET …` line are guarded by the `simplepie_syslog_enabled` setting, so adding

```php
'simplepie_syslog_enabled' => false,
```

to your `data/config.php` silences both of the lines from the original report.

If the SimplePie GET/cache noise was the main annoyance, this should cover it now. If you are also after a general "warnings and above" level across *all* of FreshRSS logging (not just SimplePie), that is a broader change worth tracking separately — otherwise this can probably be closed.

**Comment by sokai** [comment]
Thank you @JamBalaya56562 !
For me that fixes _my points_. But I have to see, how the changes show up at my machine. #TBC
May someone can answer the question, when we can expect a new version (the PR included)?
KR

**Comment by JamBalaya56562** [comment]
@sokai You're welcome! 🙂

Regarding a release date: FreshRSS doesn't follow a fixed release schedule, so I can't give you an exact date. What I can tell you:

- #8986 is already merged into the `edge` branch, so **you don't have to wait for the next stable release to test it.** The fix is live right now in the development builds.
- If you run FreshRSS via Docker, you can pull the **`freshrss/freshrss:edge`** image to verify the behaviour on your machine today (`#TBC` → resolved 😉). Just remember `edge` tracks the in-development branch, so treat it accordingly.
- It will ship in the **next stable release** (the one after 1.29.1). Based on the recent cadence (1.29.0 and 1.29.1 in May 2026), that's typically a matter of weeks-to-a-couple-of-months rather than a hard date.

Once you've had a chance to confirm it on your side, feel free to report back — and if the SimplePie noise was your main concern, this issue can probably be closed then.

**Comment by Alkarex** [comment]
> when we can expect a new version

Indeed. Our rolling release is already available, which you are welcome to use. Slow releases (which are in average not more bug-free than rolling releases, because we do not back-port fixes) are made when it makes sense on a number of criteria, for instance at the moment the focus is on internal security mechanisms

**Comment by Tone866** [comment]
looks like the setting does not affect the syslog, I still get "FreshRSS SimplePie GET 200"-Logs in the syslog with `'log_level' => 'warning'`
