### ISSUE TITLE
User queries when used in "mark as read filters" for individual feed

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#8378]
### Discussed in https://github.com/FreshRSS/FreshRSS/discussions/8377

@geogiraux

<div type='discussions-op-text'>

<sup>Originally posted by **geogiraux** December 31, 2025</sup>
I have noticed something new/strange in FreshRSS 1.28.0 : when I'm using a user query in the "mark as read" field of a specific feed, refering to it with S:X, the S:X get replaced by the full text query. while I find this a little bit harder to read and manipulate in the "mark as read" field, does it mean the field doesn't get updated anymore when the user query is edited/updated ? 
I should point out btw that I'm not using user queries for generating subfeeds but only for managing kind of generic "mark as read" filters</div>

**Comment by geogiraux** [comment]
investigating a bit further (looking at filtersActionRead of my opml.xml export), I also noticed some unexpected user queries for specific feeds, as if they were switched or as if the S:X had all been reindexed. As I'm using different user queries for french and english sources, I know have french words in english feeds. My guess from an "unexpected" index change comes from :
- the fact my 4 user queries are perfectly indexed (0,1,2,3) whereas I remember deleting one a few times ago and I don't remember using the 0 one
- I have found in one of my feed description from my opml.xml export a reference to S:4, which seems strange regarding the fact there is no more/other S:X in my opml file
nonetheless, at this point I cannot make sure it is related to the 1.28.0 release since I have noticed quite a decrease in my news, which is certainly related to this unexpected change. Maybe it came from an operation on the database itself ?

**Comment by geogiraux** [comment]
@Alkarex regarding the initial comment (bug ?), even if I find it counter intuitive and I don't get how it works on the code, it seems that editing a user query updates as expected the "mark as read" field of each feed having it.
In the end, I think the "real" or original bug is more related to an index change of user queries, which, in combination with a FreshRSS behaviour change regarding user queries, messed up a little my instance

**Comment by Alkarex** [comment]
The indexing issue you are seeing may be the one fixed in:
* https://github.com/FreshRSS/FreshRSS/pull/8113

I am working on a fix for the expansion, which should not be expanded.

**Comment by Alkarex** [comment]
@geogiraux I have made a patch:
* https://github.com/FreshRSS/FreshRSS/pull/8395

Would be able to give it a try? Tests welcome.

**Comment by geogiraux** [comment]
Thanks ! I gave it a quick try (downloading the patch file from github and applying it on my own instance) and it seems working, the S:X is no more replaced in the mark as read field. but a bit to early to check if "mark as read" is working as expected.
it also looks ok in the opml.xml export file
I have noticed the S:X still gets changed/replaced in the search bar : I don't know if it is expected. My opinion here, as a simple user, is that it is useful for quickly seeing the query if one doesn't remember, but not so useful (as in the mark as read filed) if manipulating some intricate or complex queries, but of course I leave the choice to the FreshRSS dev team
P.S. I'm not sure to understand the relation between the PR and the indexing issue (since I don't remember using drag&drop), but it's a good thing to me that you are able to explain it on your side :-)

**Comment by Alkarex** [comment]
Very good. Merged in the rolling release *edge* branch. Please update and additional tests welcome
